services:
  db:
    image: mysql:8.0
    container_name: amz-revenue-db
    restart: always
    environment:
      MYSQL_DATABASE: amazon_balance_calculation
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
